# Generated by Django 5.1.6 on 2025-03-01 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UmrahCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('limited_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Umrah.limitedoffer')),
            ],
        ),
        migrations.CreateModel(
            name='UmrahPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='umrah_images')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Umrah.umrahcategory')),
            ],
        ),
        migrations.AddField(
            model_name='limitedoffer',
            name='umrah_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Umrah.umrahpackage'),
        ),
    ]
