# Generated by Django 5.1.6 on 2025-03-06 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Umrah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedTimeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OfferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='limited_offer',
        ),
        migrations.RemoveField(
            model_name='umrahpackage',
            name='category',
        ),
        migrations.CreateModel(
            name='OfferDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('document_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offer_images')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('limited_time_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Umrah.limitedtimeoffer')),
                ('offer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Umrah.offertype')),
            ],
        ),
        migrations.AddField(
            model_name='limitedtimeoffer',
            name='offer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Umrah.offertype'),
        ),
        migrations.RenameModel(
            old_name='UmrahCategory',
            new_name='UmrahPackageCategory',
        ),
        migrations.CreateModel(
            name='UmrahDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='umrah_images')),
                ('description', models.TextField()),
                ('umrah_package_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Umrah.umrahpackagecategory')),
            ],
        ),
        migrations.AddField(
            model_name='offertype',
            name='umrah_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Umrah.umrahdetails'),
        ),
        migrations.AddField(
            model_name='limitedtimeoffer',
            name='umrah_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Umrah.umrahdetails'),
        ),
        migrations.DeleteModel(
            name='LimitedOffer',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='UmrahPackage',
        ),
    ]
