# Generated by Django 5.1.6 on 2025-03-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Umrah', '0002_limitedtimeoffer_offertype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umrahdetails',
            old_name='price',
            new_name='adult_price',
        ),
        migrations.AddField(
            model_name='umrahdetails',
            name='child_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
