# Generated by Django 5.1.6 on 2025-03-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Umrah', '0003_rename_price_umrahdetails_adult_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UmrahPackageCategory',
            new_name='UmrahCategory',
        ),
        migrations.RenameField(
            model_name='offerdetails',
            old_name='document_description',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='umrahdetails',
            old_name='umrah_package_category',
            new_name='umrah_category',
        ),
        migrations.RemoveField(
            model_name='offerdetails',
            name='image',
        ),
        migrations.RemoveField(
            model_name='offerdetails',
            name='title',
        ),
        migrations.RemoveField(
            model_name='offertype',
            name='umrah_details',
        ),
        migrations.AddField(
            model_name='limitedtimeoffer',
            name='offer_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='umrahdetails',
            name='adult_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='umrahdetails',
            name='child_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='umrahdetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='umrahdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='umrah_images'),
        ),
    ]
