# Generated by Django 5.1.6 on 2025-03-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Umrah', '0004_rename_umrahpackagecategory_umrahcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umrahcategory',
            old_name='category_name',
            new_name='umrah_category',
        ),
    ]
