# Generated by Django 5.1.6 on 2025-03-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Umrah', '0005_rename_category_name_umrahcategory_umrah_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitedtimeoffer',
            name='offer_description',
        ),
    ]
