# Generated by Django 5.1.6 on 2025-03-01 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='visa_images')),
                ('description', models.TextField()),
                ('visa_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visa.visacategory')),
            ],
        ),
    ]
