# Generated by Django 5.1.6 on 2025-03-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visa', '0003_visarequirements_visadocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='visadocuments',
            name='document_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
