# Generated by Django 5.1.6 on 2025-03-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visa', '0004_visadocuments_document_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visadetails',
            name='price',
        ),
        migrations.AddField(
            model_name='visadetails',
            name='adult_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visadetails',
            name='child_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
