# Generated by Django 5.1.6 on 2025-03-06 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visa', '0005_remove_visadetails_price_visadetails_adult_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(max_length=100)),
                ('visa_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visa.visadetails')),
            ],
        ),
        migrations.AddField(
            model_name='visadocuments',
            name='person_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Visa.persontype'),
        ),
        migrations.AlterField(
            model_name='visarequirements',
            name='person_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visa.persontype'),
        ),
    ]
