# Generated by Django 5.1.6 on 2025-03-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewHomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter banner title', max_length=255)),
                ('gif_image', models.ImageField(help_text='Upload a GIF file', upload_to='banners/gifs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
