# Generated by Django 5.1.6 on 2025-03-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_newhomebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
            ],
        ),
    ]
