# Generated by Django 5.1.6 on 2025-03-14 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='quantity',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\d+\\+?$', 'Enter a valid quantity (e.g., 50 or 50+).')]),
        ),
    ]
