# Generated by Django 5.1.6 on 2025-03-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_alter_counter_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='quantity',
        ),
        migrations.AddField(
            model_name='counter',
            name='half',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
