# Generated by Django 5.1.6 on 2025-03-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_remove_counter_quantity_counter_half'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='offer_videos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
