# Generated by Django 5.1.6 on 2025-03-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_offervideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPointBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='seobox_icon/')),
            ],
        ),
    ]
