# Generated by Django 5.1.6 on 2025-03-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0008_tourvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmrahBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter banner title', max_length=255)),
                ('image', models.ImageField(help_text='Upload an image (any format)', upload_to='banners/umrah/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
