# Generated by Django 5.1.6 on 2025-03-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0009_umrahbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyBookUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter section title', max_length=255)),
                ('description', models.TextField(help_text='Enter a brief description')),
                ('image', models.ImageField(help_text='Upload an image (any format)', upload_to='whybookus/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
