# Generated by Django 5.1.6 on 2025-03-01 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('price_per_day', models.IntegerField()),
                ('model_from', models.PositiveSmallIntegerField(default=2000)),
                ('model_to', models.PositiveSmallIntegerField(default=2025)),
                ('image', models.ImageField(upload_to='car_images')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarRental.carcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField()),
                ('car_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarRental.cardetails')),
            ],
        ),
    ]
