# Generated by Django 5.1.6 on 2025-03-13 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsandconditions',
            name='car_details',
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model_from', models.PositiveSmallIntegerField(default=2000)),
                ('model_to', models.PositiveSmallIntegerField(default=2025)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='CarRental.carcategory')),
            ],
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms_conditions', to='CarRental.car'),
        ),
        migrations.CreateModel(
            name='CarRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_within_city_before', models.DecimalField(decimal_places=2, help_text='Previous rent within the city', max_digits=10)),
                ('rent_within_city_after', models.DecimalField(decimal_places=2, help_text='Current rent within the city', max_digits=10)),
                ('rent_out_of_station_before', models.DecimalField(decimal_places=2, help_text='Previous rent out of station', max_digits=10)),
                ('rent_out_of_station_after', models.DecimalField(decimal_places=2, help_text='Current rent out of station', max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_info', to='CarRental.car')),
            ],
        ),
        migrations.DeleteModel(
            name='CarDetails',
        ),
    ]
