# Generated by Django 5.1.6 on 2025-03-13 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0002_remove_termsandconditions_car_details_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms_conditions', to='CarRental.car'),
        ),
    ]
