# Generated by Django 5.1.6 on 2025-03-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0003_alter_termsandconditions_car'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermsAndConditions',
            new_name='CarTermsAndConditions',
        ),
    ]
