# Generated by Django 5.1.6 on 2025-03-01 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='tour_images')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.tourcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TourLimitedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(max_length=100)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='BookingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flying_from', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='TourPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('tour_limited_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.tourlimitedoffer')),
            ],
        ),
        migrations.CreateModel(
            name='VisaRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(max_length=100)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='VisaDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('document_description', models.TextField(blank=True, null=True)),
                ('visa_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.visarequirements')),
            ],
        ),
    ]
