# Generated by Django 5.1.6 on 2025-03-12 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryMeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tourlimitedoffer',
            name='tour_package',
        ),
        migrations.RemoveField(
            model_name='tourplace',
            name='tour_limited_offer',
        ),
        migrations.RemoveField(
            model_name='visadocuments',
            name='visa_requirement',
        ),
        migrations.RemoveField(
            model_name='visarequirements',
            name='tour_package',
        ),
        migrations.RenameField(
            model_name='termsandconditions',
            old_name='description',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='termsandconditions',
            name='title',
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Tour.tourcategory'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_packages/'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='HotelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=3)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.tourpackage')),
                ('services', models.ManyToManyField(blank=True, related_name='hotel_services', to='Tour.hotelservice')),
            ],
        ),
        migrations.CreateModel(
            name='InclusionExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='itineraries/')),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.tourpackage')),
                ('meals', models.ManyToManyField(blank=True, related_name='itinerary_meals', to='Tour.itinerarymeals')),
                ('activities', models.ManyToManyField(blank=True, related_name='itinerary_services', to='Tour.itineraryservice')),
            ],
        ),
        migrations.CreateModel(
            name='VisaRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_type', models.CharField(max_length=255)),
                ('document_name', models.CharField(max_length=255)),
                ('document_details', models.TextField()),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.tourpackage')),
            ],
        ),
        migrations.DeleteModel(
            name='ItineraryDay',
        ),
        migrations.DeleteModel(
            name='TourLimitedOffer',
        ),
        migrations.DeleteModel(
            name='TourPlace',
        ),
        migrations.DeleteModel(
            name='VisaDocuments',
        ),
        migrations.DeleteModel(
            name='VisaRequirements',
        ),
    ]
