# Generated by Django 5.1.6 on 2025-03-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0002_hotelservice_itinerarymeals_itineraryservice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visarequirement',
            old_name='visa_type',
            new_name='person_type',
        ),
    ]
